name			= "Bravo Company Aux";					// Name of your mod
author			= "Queen";				// Affects Arma 3 Launcher, when the mod are loaded as local
logo			= "BCR_Core\data\logo_ca.paa";			// Logo displayed in the main menu
logoOver		= "BCR_Core\data\logo_ca.paa";	// When the mouse is over, in the main menu
tooltip			= "BCR";
tooltipOwned	= "hi";				// Tool tip displayed when the mouse is left over, in the main menu
picture			= "";		// Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName		= "GitHub";
action			= "https://github.com/BeaniePope/Bravo-Company-Aux";			// Website URL, that can be accessed from the expansions menu
overview		= "Bravo Company Aux Mod";	// Supports structured text
hideName		= 0;						// Hide the extension name
hidePicture		= 0;						// Hide the extension menu
dlcColor[]		= { 0.23, 0.39, 0.30, 1 };	// Color used for DLC stripes and backgrounds (RGBA)
logoSmall		= "BCR_Core\data\logo_ca.paa";		// Display in creative lists, next to the entities added by the mod
